### ISSUE TITLE
escape.literal throws `val.indexOf is not a function` for numbers and booleans

### ISSUE THREAD

**Issue by thesmart** [segmentio/pg-escape#15]
v0.2.0 doesn't seem to handle literals:

```
> escape.literal(true);
TypeError: val.indexOf is not a function
    at Function.exports.literal (/Users/smart/figma/web/lambda/figlytics/node_modules/pg-escape/index.js:125:24)
    at repl:1:8
    at REPLServer.defaultEval (repl.js:262:27)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:431:12)
    at emitOne (events.js:82:20)
    at REPLServer.emit (events.js:169:7)
    at REPLServer.Interface._onLine (readline.js:211:10)
    at REPLServer.Interface._line (readline.js:550:8)
```

```
> escape.literal(1);
TypeError: val.indexOf is not a function
    at Function.exports.literal (/Users/smart/figma/web/lambda/figlytics/node_modules/pg-escape/index.js:125:24)
    at repl:1:8
    at REPLServer.defaultEval (repl.js:262:27)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:431:12)
    at emitOne (events.js:82:20)
    at REPLServer.emit (events.js:169:7)
    at REPLServer.Interface._onLine (readline.js:211:10)
    at REPLServer.Interface._line (readline.js:550:8)
```

I had always figured a literal is an explicit numeric, character, string, or Boolean value not represented by an identifier.

**Comment by Felix-N** [comment]
+1

**Comment by nunesbeto** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by artahian** [comment]
+1
